version: "3"
services:
    db:
        image: "microsoft/mssql-server-linux"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "w@terb0y"
            ACCEPT_EULA: "Y"
        volumes:
          - ./data/mssql:/var/opt/mssql

volumes:
  db_data: